AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'AWS SAM template for scheduling Lambda function using EventBridge and sending database patch notifications by SNS'


Parameters:
  EmailAddress:
    Type: String
    Description: 'Email address to subscribe to the SNS topic'
  #Clusterlist:
  #   Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
  #  Description: 'docDB Cluster list for patch delay'
  #  Default: 'clustera,clusterb'

Resources:
  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: 'AWS DB Patch Delay Notifications'
      TopicName: 'docdb-patch-delay-notification'
      Subscription:
        - Protocol: 'email'
          Endpoint: !Ref EmailAddress
    #ClusterListPaStore:
    #Type: AWS::SSM::Parameter
    #Properties:
    #  Name: patch-delay-cluster-list
    #  Type: StringList
    #  Value: !Ref Clusterlist
    #  Description: SSM Parameter of type StringList.
      #AllowedPattern: "^[a-zA-Z]{1,10}$"

  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: './lambda/'
      Handler: index.lambda_handler
      Runtime: python3.10
      MemorySize: 128
      Timeout: 420
      Policies: 
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sns:Publish'
                - 'ec2:DescribeRegions'
                - 'rds:DescribeDBInstances'
                - 'rds:DescribePendingMaintenanceActions'
                - 'rds:DescribeDBClusters'
                - 'rds:ModifyDBCluster'
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
                - 'kms:CreateGrant'
                - 'kms:DescribeKey'
                - 'kms:GenerateDataKey'
                - 'kms:Decrypt'
                - 'secretsmanager:CreateSecret'
                - 'secretsmanager:TagResource'
                - 'secretsmanager:RotateSecret'
                - 'ssm:Describe'
                - 'ssm:GetParameter'
                - 'ssm:Get'
                - 'ssm:List'
              Resource: '*'
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSTopic
            #clusterlist_ARN: !Ref ClusterListPaStore
      Events:
        ScheduledEvent:
          Type: 'Schedule'
          Properties:
            Enabled: true
            Name: 'db-patch-delay-Schedule'
            Description: 'Schedule for scanning database patches'
            Schedule: 'cron(0 0 * * ? *)' # Replace with desired schedule expression

Outputs:
  LambdaFunctionName:
    Value: !Ref LambdaFunction
  SNSTopicName:
    Value: !Ref SNSTopic
